version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: 'example'
      POSTGRES_PASSWORD: 'example'
      POSTGRES_DB: 'example'
    ports:
      - '5432:5432'
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d